### ISSUE TITLE
Is this program compatible with python 3.12?

### ISSUE THREAD

**Issue by AnthonyWu0709** [DemonicSavage/mikan#67]
I just uploaded my python version from 3.11 to 3.12 by simply just deleting older one and installing new one.
When I tried `pip install mikan-card-downloader` after `pip install poetry`, something wrong happened.
[ErrorMsg.txt](https://github.com/DemonicSavage/mikan/files/13072740/ErrorMsg.txt)

**Comment by AnthonyWu0709** [comment]
It seems that it was definitely the problem of the new python, as i installed it successfully with python 3.11.6

**Comment by DemonicSavage** [comment]
Unfortunately, it doesn't yet work with Python 3.12.

That's because one of the dependencies [doesn't yet support it](https://github.com/aio-libs/aiohttp/issues/7675).

For now, I recommend installing this through `pipx` like recommended in the README. That will install Mikan into its own 3.11 environment, letting your systems' Python 3.12 for other things.

As soon as aiohttp 3.9 is released, I will update Mikan to use 3.12.

**Comment by DemonicSavage** [comment]
I will leave this open until it's fixed.

**Comment by DemonicSavage** [comment]
I have created a beta version of Mikan which uses `aiohttp==3.9.0b0`, which supports Python 3.12.

If you are interested in installing it, use `pipx install mikan-card-downloader==2.1.6b0`. You might need to uninstall the current version of Mikan you currently have.

**Comment by DemonicSavage** [comment]
It's done. :)
